/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TestCounterInterface extends ethers.utils.Interface {
  functions: {
    "count()": FunctionFragment;
    "counters(address)": FunctionFragment;
    "gasWaster(uint256,string)": FunctionFragment;
    "justemit()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "count", values?: undefined): string;
  encodeFunctionData(functionFragment: "counters", values: [string]): string;
  encodeFunctionData(
    functionFragment: "gasWaster",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "justemit", values?: undefined): string;

  decodeFunctionResult(functionFragment: "count", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "counters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gasWaster", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "justemit", data: BytesLike): Result;

  events: {
    "CalledFrom(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CalledFrom"): EventFragment;
}

export type CalledFromEvent = TypedEvent<[string] & { sender: string }>;

export class TestCounter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TestCounterInterface;

  functions: {
    count(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    counters(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    gasWaster(
      repeat: BigNumberish,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    justemit(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  count(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  counters(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  gasWaster(
    repeat: BigNumberish,
    arg1: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  justemit(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    count(overrides?: CallOverrides): Promise<void>;

    counters(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    gasWaster(
      repeat: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    justemit(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "CalledFrom(address)"(
      sender?: null
    ): TypedEventFilter<[string], { sender: string }>;

    CalledFrom(sender?: null): TypedEventFilter<[string], { sender: string }>;
  };

  estimateGas: {
    count(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    counters(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    gasWaster(
      repeat: BigNumberish,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    justemit(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    count(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    counters(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gasWaster(
      repeat: BigNumberish,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    justemit(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
